<?php 
	$this->assets->outputCss(); 
?>

<div class="page-header">
    <h1>Episodios</h1>
</div>

<section id="seccion-episodios-tarjetas">
	<div id="contenedor-episodios-tarjetas">
		
	</div>
</section>

<section id="seccion-episodios-datatables">
	<div class="row">
		<div class="col s12">
			<p class="range-field">
				<input type="range" id="rango_id" min="0" max="20" />
				<span class="thumb" style="height: 0px; width: 0px; top: 10px; margin-left: 7px; left: 198.564px;">
					<span class="value">28</span>
				</span>
			</p>
		</div>
	</div>
	<div class="row">
		<div class="col s12">
			<table id="tabla-episodios">
				<thead>
					<tr>
						<th>ID</th>
						<th>Name</th>
						<th>Air Date</th>
						<th>Episode</th>
						<th>Characters</th>
						<th>URL</th>
						<th>Created</th>
					</tr>
				</thead>
				<tbody>
				
				</tbody>
			</table>
		</div>
	</div>
</section>

<?php 
	$this->assets->outputJs(); 
?>

