<?php 
	$this->assets->outputCss(); 
?>

<div class="page-header">
    <h1>Episodios</h1>
</div>

<section id="seccion-episodios-tarjetas">
	<div id="contenedor-episodios-tarjetas">
		
	</div>
</section>

<section id="seccion-episodios-datatables">
	<div class="row">
		<div class="col s12">
			<table id="tabla-episodios">
				<thead>
					<tr>
						<th>ID</th>
						<th>Name</th>
						<th>Air Date</th>
						<th>Episode</th>
						<th>Characters</th>
						<th>URL</th>
						<th>Created</th>
					</tr>
				</thead>
				<tbody>
				
				</tbody>
			</table>
		</div>
	</div>
</section>

<?php 
	$this->assets->outputJs(); 
?>

